name: Update awesome list

on: 
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Awesome generator
        uses: simonecorsi/mawesome@v2
        with:
          template-path: "template/README.ejs"
          api-token: ${{ secrets.API_TOKEN }}
          
      - name: Generate README
        run: python generate.py

      - name: Commit README
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "update lists"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
